import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Box, Button, ChakraProvider, extendTheme, Text } from '@chakra-ui/react'
import useUser from '../app/useUser'
import { getUser } from '../app/services/UserService'
import { useEffect } from 'react'
import { initializeApp } from 'firebase/app'
import { firebaseConfig } from '../firebaseConfig'

const Home: NextPage = () => {

  const { setUser } = useUser();

  const login = ()=>{
    const user = prompt("Escriba nombre de usuario");

    initializeApp(firebaseConfig);
    getUser(user!,"").then(x=>{
      setUser(x);
      alert(`Usuario ${x.fullName} asignado`);
    });

  }

  return (
    
    <ChakraProvider theme={{
      colors:{
        primary: "red"
      }
    }}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <button onClick={login}>
          Login
        </button>
      </div>
    </ChakraProvider>
  )
}

export default Home
